services:
  whisper:
    image: dockerregistry.csrdigas.es/whisper:v1.2
    container_name: whisper-service
    restart: unless-stopped
    dns:
      - 10.236.203.11
    ports:
      - "8000:8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whisper.rule=Host(`whisper.example.com`)"
      - "traefik.http.routers.whisper.entrypoints=websecure"
      - "traefik.http.routers.whisper.tls=true"
      - "traefik.http.services.whisper.loadbalancer.server.port=8000"
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - WHISPERX_DEVICE=cuda
      - WHISPERX_MODEL=${WHISPERX_MODEL:-large-v3}
      - WHISPERX_COMPUTE_TYPE=${WHISPERX_COMPUTE_TYPE:-int8_float16}
      - WHISPERX_BATCH_SIZE=${WHISPERX_BATCH_SIZE:-1}
      - XDG_CACHE_HOME=/home/appuser/.cache
      - HF_HOME=/home/appuser/.cache/huggingface
      - HF_HUB_CACHE=/home/appuser/.cache/huggingface/hub
      - TORCH_HOME=/home/appuser/.cache/torch
      - XDG_CONFIG_HOME=/tmp/app-config
      - MPLCONFIGDIR=/tmp/matplotlib
      - HOME=/home/appuser
      - NLTK_DATA=/home/appuser/nltk_data
      - API_KEY=pruebakey
      - HF_TOKEN=${HF_TOKEN:-}
      - WHISPERX_DIARIZATION_MODEL=${WHISPERX_DIARIZATION_MODEL:-pyannote/speaker-diarization-3.1}
      - AUDIO_CLEANING_DEEPFILTER_MODEL=${AUDIO_CLEANING_DEEPFILTER_MODEL:-DeepFilterNet3}
      - AUDIO_CLEANING_NOISE_ATTENUATION_PERCENT=${AUDIO_CLEANING_NOISE_ATTENUATION_PERCENT:-100}
      - AUDIO_CLEANING_TARGET_LOUDNESS_LUFS=${AUDIO_CLEANING_TARGET_LOUDNESS_LUFS:--16}
      - AUDIO_CLEANING_TRUE_PEAK_DB=${AUDIO_CLEANING_TRUE_PEAK_DB:--1.5}
      - NVIDIA_VISIBLE_DEVICES=0
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./whisper/models:/home/appuser
      - ./whisper/tmp:/tmp/whisper
    security_opt:
      - no-new-privileges:true
    user: "1000:1000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
    networks:
      - traefik_default

  model-downloader:
    image: dockerregistry.csrdigas.es/whisper:v1.2
    container_name: whisper-model-downloader
    profiles: ["setup"]   # solo se ejecuta si activas este profile
    dns:
      - 10.236.203.11
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - WHISPERX_DEVICE=cuda
      - WHISPERX_MODEL=${WHISPERX_MODEL:-large-v3}
      - WHISPERX_COMPUTE_TYPE=${WHISPERX_COMPUTE_TYPE:-int8_float16}
      - WHISPERX_BATCH_SIZE=${WHISPERX_BATCH_SIZE:-1}
      - WHISPERX_PRELOAD_DIARIZATION=${WHISPERX_PRELOAD_DIARIZATION:-true}
      - WHISPERX_PRELOAD_ALIGN_LANGUAGES=${WHISPERX_PRELOAD_ALIGN_LANGUAGES:-}
      - XDG_CACHE_HOME=/home/appuser/.cache
      - HF_HOME=/home/appuser/.cache/huggingface
      - HF_HUB_CACHE=/home/appuser/.cache/huggingface/hub
      - TORCH_HOME=/home/appuser/.cache/torch
      - XDG_CONFIG_HOME=/tmp/app-config
      - MPLCONFIGDIR=/tmp/matplotlib
      - HOME=/home/appuser
      - NLTK_DATA=/home/appuser/nltk_data
      - HF_TOKEN=${HF_TOKEN:-}
      - WHISPERX_DIARIZATION_MODEL=${WHISPERX_DIARIZATION_MODEL:-pyannote/speaker-diarization-3.1}
      - WHISPERX_PRELOAD_MODEL=${WHISPERX_PRELOAD_MODEL:-true}
      - AUDIO_CLEANING_PRELOAD_DEEPFILTER=${AUDIO_CLEANING_PRELOAD_DEEPFILTER:-true}
      - AUDIO_CLEANING_DEEPFILTER_MODEL=${AUDIO_CLEANING_DEEPFILTER_MODEL:-DeepFilterNet3}
    volumes:
      - ./whisper/models:/home/appuser
    command: ["bash", "/app/entrypoint.sh", "python3", "/app/preload_models.py"]
    networks:
      - traefik_default
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]

networks:
  traefik_default:
    external: true
